// Generated by scripts/import-legal.ts on 2026-09-28. Do not edit by hand, rerun `pnpm import:legal`.
// Source: https://api.sejm.gov.pl/eli/acts (Sejm ELI API, the data behind ISAP).

export const acts = [
  {
    "slug": "ustawa-2019-848",
    "eli": "DU/2019/848",
    "title": "Ustawa z dnia 4 kwietnia 2019 r. o dostępności cyfrowej stron internetowych i aplikacji mobilnych podmiotów publicznych",
    "address": "Dz.U. 2019 poz. 848",
    "isap": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20190000848",
    "inForce": "2019-05-23",
    "consolidated": {
      "eli": "DU/2023/1440",
      "address": "Dz.U. 2023 poz. 1440",
      "date": "2023-07-07"
    },
    "retrieved": "2026-09-28",
    "complete": true,
    "amendedAfter": [],
    "chapters": []
  },
  {
    "slug": "ustawa-2019-1696",
    "eli": "DU/2019/1696",
    "title": "Ustawa z dnia 19 lipca 2019 r. o zapewnianiu dostępności osobom ze szczególnymi potrzebami",
    "address": "Dz.U. 2019 poz. 1696",
    "isap": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20190001696",
    "inForce": "2019-09-20",
    "consolidated": {
      "eli": "DU/2024/1411",
      "address": "Dz.U. 2024 poz. 1411",
      "date": "2024-09-18"
    },
    "retrieved": "2026-09-28",
    "complete": false,
    "amendedAfter": [
      {
        "eli": "DU/2024/731",
        "label": "Dz.U. 2024 poz. 731",
        "from": "2025-06-28"
      }
    ],
    "chapters": [
      {
        "number": 1,
        "title": "Przepisy ogólne"
      },
      {
        "number": 2,
        "title": "Koordynacja zapewniania dostępności osobom ze szczególnymi potrzebami"
      },
      {
        "number": 4,
        "title": "Postępowanie skargowe"
      }
    ]
  },
  {
    "slug": "ustawa-2024-731",
    "eli": "DU/2024/731",
    "title": "Ustawa z dnia 26 kwietnia 2024 r. o zapewnianiu spełniania wymagań dostępności niektórych produktów i usług przez podmioty gospodarcze",
    "address": "Dz.U. 2024 poz. 731",
    "isap": "https://isap.sejm.gov.pl/isap.nsf/DocDetails.xsp?id=WDU20240000731",
    "inForce": "2025-06-28",
    "consolidated": null,
    "retrieved": "2026-09-28",
    "complete": false,
    "amendedAfter": [],
    "chapters": [
      {
        "number": 1,
        "title": "Przepisy ogólne"
      },
      {
        "number": 2,
        "title": "Zapewnianie spełniania wymagań dostępności produktów i usług"
      },
      {
        "number": 3,
        "title": "Obowiązki podmiotów gospodarczych"
      },
      {
        "number": 4,
        "title": "Dochodzenie praw przez konsumentów"
      },
      {
        "number": 6,
        "title": "Przepisy o karach pieniężnych"
      },
      {
        "number": 8,
        "title": "Przepisy przejściowe i dostosowujące oraz przepis końcowy"
      }
    ]
  }
] as const;

/** Articles in scope, plus the annex of the 2019 act, in statute order. */
export const legalUnits = [
  {
    "id": "ustawa-2019-848/art-1",
    "act": "ustawa-2019-848",
    "slug": "art-1",
    "label": "Art. 1",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-2",
    "act": "ustawa-2019-848",
    "slug": "art-2",
    "label": "Art. 2",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-3",
    "act": "ustawa-2019-848",
    "slug": "art-3",
    "label": "Art. 3",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-4",
    "act": "ustawa-2019-848",
    "slug": "art-4",
    "label": "Art. 4",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-5",
    "act": "ustawa-2019-848",
    "slug": "art-5",
    "label": "Art. 5",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-5a",
    "act": "ustawa-2019-848",
    "slug": "art-5a",
    "label": "Art. 5a",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-6",
    "act": "ustawa-2019-848",
    "slug": "art-6",
    "label": "Art. 6",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-7",
    "act": "ustawa-2019-848",
    "slug": "art-7",
    "label": "Art. 7",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-8",
    "act": "ustawa-2019-848",
    "slug": "art-8",
    "label": "Art. 8",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-9",
    "act": "ustawa-2019-848",
    "slug": "art-9",
    "label": "Art. 9",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-10",
    "act": "ustawa-2019-848",
    "slug": "art-10",
    "label": "Art. 10",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-11",
    "act": "ustawa-2019-848",
    "slug": "art-11",
    "label": "Art. 11",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-12",
    "act": "ustawa-2019-848",
    "slug": "art-12",
    "label": "Art. 12",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-13",
    "act": "ustawa-2019-848",
    "slug": "art-13",
    "label": "Art. 13",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-14",
    "act": "ustawa-2019-848",
    "slug": "art-14",
    "label": "Art. 14",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-15",
    "act": "ustawa-2019-848",
    "slug": "art-15",
    "label": "Art. 15",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-16",
    "act": "ustawa-2019-848",
    "slug": "art-16",
    "label": "Art. 16",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-17",
    "act": "ustawa-2019-848",
    "slug": "art-17",
    "label": "Art. 17",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-18",
    "act": "ustawa-2019-848",
    "slug": "art-18",
    "label": "Art. 18",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-19",
    "act": "ustawa-2019-848",
    "slug": "art-19",
    "label": "Art. 19",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-20",
    "act": "ustawa-2019-848",
    "slug": "art-20",
    "label": "Art. 20",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-21",
    "act": "ustawa-2019-848",
    "slug": "art-21",
    "label": "Art. 21",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-22",
    "act": "ustawa-2019-848",
    "slug": "art-22",
    "label": "Art. 22",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-23",
    "act": "ustawa-2019-848",
    "slug": "art-23",
    "label": "Art. 23",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-24",
    "act": "ustawa-2019-848",
    "slug": "art-24",
    "label": "Art. 24",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-25",
    "act": "ustawa-2019-848",
    "slug": "art-25",
    "label": "Art. 25",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-26",
    "act": "ustawa-2019-848",
    "slug": "art-26",
    "label": "Art. 26",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/art-27",
    "act": "ustawa-2019-848",
    "slug": "art-27",
    "label": "Art. 27",
    "chapter": null
  },
  {
    "id": "ustawa-2019-848/zal",
    "act": "ustawa-2019-848",
    "slug": "zal",
    "label": "Załącznik",
    "chapter": null
  },
  {
    "id": "ustawa-2019-1696/art-1",
    "act": "ustawa-2019-1696",
    "slug": "art-1",
    "label": "Art. 1",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-2",
    "act": "ustawa-2019-1696",
    "slug": "art-2",
    "label": "Art. 2",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-3",
    "act": "ustawa-2019-1696",
    "slug": "art-3",
    "label": "Art. 3",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-4",
    "act": "ustawa-2019-1696",
    "slug": "art-4",
    "label": "Art. 4",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-5",
    "act": "ustawa-2019-1696",
    "slug": "art-5",
    "label": "Art. 5",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-6",
    "act": "ustawa-2019-1696",
    "slug": "art-6",
    "label": "Art. 6",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-7",
    "act": "ustawa-2019-1696",
    "slug": "art-7",
    "label": "Art. 7",
    "chapter": 1
  },
  {
    "id": "ustawa-2019-1696/art-14",
    "act": "ustawa-2019-1696",
    "slug": "art-14",
    "label": "Art. 14",
    "chapter": 2
  },
  {
    "id": "ustawa-2019-1696/art-29",
    "act": "ustawa-2019-1696",
    "slug": "art-29",
    "label": "Art. 29",
    "chapter": 4
  },
  {
    "id": "ustawa-2019-1696/art-30",
    "act": "ustawa-2019-1696",
    "slug": "art-30",
    "label": "Art. 30",
    "chapter": 4
  },
  {
    "id": "ustawa-2019-1696/art-31",
    "act": "ustawa-2019-1696",
    "slug": "art-31",
    "label": "Art. 31",
    "chapter": 4
  },
  {
    "id": "ustawa-2019-1696/art-32",
    "act": "ustawa-2019-1696",
    "slug": "art-32",
    "label": "Art. 32",
    "chapter": 4
  },
  {
    "id": "ustawa-2019-1696/art-33",
    "act": "ustawa-2019-1696",
    "slug": "art-33",
    "label": "Art. 33",
    "chapter": 4
  },
  {
    "id": "ustawa-2019-1696/art-34",
    "act": "ustawa-2019-1696",
    "slug": "art-34",
    "label": "Art. 34",
    "chapter": 4
  },
  {
    "id": "ustawa-2024-731/art-1",
    "act": "ustawa-2024-731",
    "slug": "art-1",
    "label": "Art. 1",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-2",
    "act": "ustawa-2024-731",
    "slug": "art-2",
    "label": "Art. 2",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-3",
    "act": "ustawa-2024-731",
    "slug": "art-3",
    "label": "Art. 3",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-4",
    "act": "ustawa-2024-731",
    "slug": "art-4",
    "label": "Art. 4",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-5",
    "act": "ustawa-2024-731",
    "slug": "art-5",
    "label": "Art. 5",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-6",
    "act": "ustawa-2024-731",
    "slug": "art-6",
    "label": "Art. 6",
    "chapter": 1
  },
  {
    "id": "ustawa-2024-731/art-7",
    "act": "ustawa-2024-731",
    "slug": "art-7",
    "label": "Art. 7",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-8",
    "act": "ustawa-2024-731",
    "slug": "art-8",
    "label": "Art. 8",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-9",
    "act": "ustawa-2024-731",
    "slug": "art-9",
    "label": "Art. 9",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-10",
    "act": "ustawa-2024-731",
    "slug": "art-10",
    "label": "Art. 10",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-11",
    "act": "ustawa-2024-731",
    "slug": "art-11",
    "label": "Art. 11",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-12",
    "act": "ustawa-2024-731",
    "slug": "art-12",
    "label": "Art. 12",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-13",
    "act": "ustawa-2024-731",
    "slug": "art-13",
    "label": "Art. 13",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-14",
    "act": "ustawa-2024-731",
    "slug": "art-14",
    "label": "Art. 14",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-15",
    "act": "ustawa-2024-731",
    "slug": "art-15",
    "label": "Art. 15",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-16",
    "act": "ustawa-2024-731",
    "slug": "art-16",
    "label": "Art. 16",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-17",
    "act": "ustawa-2024-731",
    "slug": "art-17",
    "label": "Art. 17",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-18",
    "act": "ustawa-2024-731",
    "slug": "art-18",
    "label": "Art. 18",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-19",
    "act": "ustawa-2024-731",
    "slug": "art-19",
    "label": "Art. 19",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-20",
    "act": "ustawa-2024-731",
    "slug": "art-20",
    "label": "Art. 20",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-21",
    "act": "ustawa-2024-731",
    "slug": "art-21",
    "label": "Art. 21",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-22",
    "act": "ustawa-2024-731",
    "slug": "art-22",
    "label": "Art. 22",
    "chapter": 2
  },
  {
    "id": "ustawa-2024-731/art-23",
    "act": "ustawa-2024-731",
    "slug": "art-23",
    "label": "Art. 23",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-24",
    "act": "ustawa-2024-731",
    "slug": "art-24",
    "label": "Art. 24",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-25",
    "act": "ustawa-2024-731",
    "slug": "art-25",
    "label": "Art. 25",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-26",
    "act": "ustawa-2024-731",
    "slug": "art-26",
    "label": "Art. 26",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-27",
    "act": "ustawa-2024-731",
    "slug": "art-27",
    "label": "Art. 27",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-28",
    "act": "ustawa-2024-731",
    "slug": "art-28",
    "label": "Art. 28",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-29",
    "act": "ustawa-2024-731",
    "slug": "art-29",
    "label": "Art. 29",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-30",
    "act": "ustawa-2024-731",
    "slug": "art-30",
    "label": "Art. 30",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-31",
    "act": "ustawa-2024-731",
    "slug": "art-31",
    "label": "Art. 31",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-32",
    "act": "ustawa-2024-731",
    "slug": "art-32",
    "label": "Art. 32",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-33",
    "act": "ustawa-2024-731",
    "slug": "art-33",
    "label": "Art. 33",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-34",
    "act": "ustawa-2024-731",
    "slug": "art-34",
    "label": "Art. 34",
    "chapter": 3
  },
  {
    "id": "ustawa-2024-731/art-35",
    "act": "ustawa-2024-731",
    "slug": "art-35",
    "label": "Art. 35",
    "chapter": 4
  },
  {
    "id": "ustawa-2024-731/art-36",
    "act": "ustawa-2024-731",
    "slug": "art-36",
    "label": "Art. 36",
    "chapter": 4
  },
  {
    "id": "ustawa-2024-731/art-37",
    "act": "ustawa-2024-731",
    "slug": "art-37",
    "label": "Art. 37",
    "chapter": 4
  },
  {
    "id": "ustawa-2024-731/art-73",
    "act": "ustawa-2024-731",
    "slug": "art-73",
    "label": "Art. 73",
    "chapter": 6
  },
  {
    "id": "ustawa-2024-731/art-84",
    "act": "ustawa-2024-731",
    "slug": "art-84",
    "label": "Art. 84",
    "chapter": 8
  },
  {
    "id": "ustawa-2024-731/art-85",
    "act": "ustawa-2024-731",
    "slug": "art-85",
    "label": "Art. 85",
    "chapter": 8
  },
  {
    "id": "ustawa-2024-731/art-86",
    "act": "ustawa-2024-731",
    "slug": "art-86",
    "label": "Art. 86",
    "chapter": 8
  },
  {
    "id": "ustawa-2024-731/art-87",
    "act": "ustawa-2024-731",
    "slug": "art-87",
    "label": "Art. 87",
    "chapter": 8
  },
  {
    "id": "ustawa-2024-731/art-88",
    "act": "ustawa-2024-731",
    "slug": "art-88",
    "label": "Art. 88",
    "chapter": 8
  }
] as const;
