// Generated by scripts/import-wcag.ts on 2026-09-27. Do not edit by hand, rerun `pnpm import:wcag`.
// Structure: https://www.w3.org/WAI/WCAG22/wcag.json
// Names: https://www.w3.org/Translations/WCAG21-pl/ (nameSource "w3c", authorized translation of WCAG 2.1)
//        https://wcag.irdpl.pl/guidelines/22/ (nameSource "irdpl", unofficial translation of WCAG 2.2)

export const principles = [
  {
    "num": "1",
    "name": "Postrzegalność"
  },
  {
    "num": "2",
    "name": "Funkcjonalność"
  },
  {
    "num": "3",
    "name": "Zrozumiałość"
  },
  {
    "num": "4",
    "name": "Solidność"
  }
] as const;

export const guidelines = [
  {
    "num": "1.1",
    "name": "Alternatywa tekstowa",
    "principle": "1"
  },
  {
    "num": "1.2",
    "name": "Multimedia",
    "principle": "1"
  },
  {
    "num": "1.3",
    "name": "Możliwość adaptacji",
    "principle": "1"
  },
  {
    "num": "1.4",
    "name": "Rozróżnialność",
    "principle": "1"
  },
  {
    "num": "2.1",
    "name": "Dostępność z klawiatury",
    "principle": "2"
  },
  {
    "num": "2.2",
    "name": "Wystarczający czas",
    "principle": "2"
  },
  {
    "num": "2.3",
    "name": "Ataki padaczki",
    "principle": "2"
  },
  {
    "num": "2.4",
    "name": "Możliwość nawigacji",
    "principle": "2"
  },
  {
    "num": "2.5",
    "name": "Metody obsługi",
    "principle": "2"
  },
  {
    "num": "3.1",
    "name": "Możliwość odczytania",
    "principle": "3"
  },
  {
    "num": "3.2",
    "name": "Przewidywalność",
    "principle": "3"
  },
  {
    "num": "3.3",
    "name": "Pomoc przy wprowadzaniu informacji",
    "principle": "3"
  },
  {
    "num": "4.1",
    "name": "Kompatybilność",
    "principle": "4"
  }
] as const;

export const criteria = [
  {
    "id": "1.1.1",
    "w3cId": "non-text-content",
    "name": "Treść nietekstowa",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.1",
    "principle": "1"
  },
  {
    "id": "1.2.1",
    "w3cId": "audio-only-and-video-only-prerecorded",
    "name": "Tylko audio lub tylko wideo (nagranie)",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.2",
    "w3cId": "captions-prerecorded",
    "name": "Napisy rozszerzone (nagranie)",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.3",
    "w3cId": "audio-description-or-media-alternative-prerecorded",
    "name": "Audiodeskrypcja lub alternatywa tekstowa dla mediów (nagranie)",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.4",
    "w3cId": "captions-live",
    "name": "Napisy rozszerzone (na żywo)",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.5",
    "w3cId": "audio-description-prerecorded",
    "name": "Audiodeskrypcja (nagranie)",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.6",
    "w3cId": "sign-language-prerecorded",
    "name": "Język migowy (nagranie)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.7",
    "w3cId": "extended-audio-description-prerecorded",
    "name": "Rozszerzona audiodeskrypcja (nagranie)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.8",
    "w3cId": "media-alternative-prerecorded",
    "name": "Alternatywa dla mediów (nagranie)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.2.9",
    "w3cId": "audio-only-live",
    "name": "Tylko audio (na żywo)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.2",
    "principle": "1"
  },
  {
    "id": "1.3.1",
    "w3cId": "info-and-relationships",
    "name": "Informacje i relacje",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.3.2",
    "w3cId": "meaningful-sequence",
    "name": "Zrozumiała kolejność",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.3.3",
    "w3cId": "sensory-characteristics",
    "name": "Właściwości zmysłowe",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.3.4",
    "w3cId": "orientation",
    "name": "Orientacja",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.3.5",
    "w3cId": "identify-input-purpose",
    "name": "Określenie pożądanej wartości",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.3.6",
    "w3cId": "identify-purpose",
    "name": "Określenie przeznaczenia",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.3",
    "principle": "1"
  },
  {
    "id": "1.4.1",
    "w3cId": "use-of-color",
    "name": "Użycie koloru",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.2",
    "w3cId": "audio-control",
    "name": "Kontrola odtwarzania dźwięku",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.3",
    "w3cId": "contrast-minimum",
    "name": "Kontrast (minimum)",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.4",
    "w3cId": "resize-text",
    "name": "Zmiana rozmiaru tekstu",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.5",
    "w3cId": "images-of-text",
    "name": "Obrazy tekstu",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.6",
    "w3cId": "contrast-enhanced",
    "name": "Kontrast (wzmocniony)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.7",
    "w3cId": "low-or-no-background-audio",
    "name": "Niska głośność lub bez dźwięków w tle",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.8",
    "w3cId": "visual-presentation",
    "name": "Prezentacja wizualna",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.9",
    "w3cId": "images-of-text-no-exception",
    "name": "Obrazy tekstu (bez wyjątków)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.10",
    "w3cId": "reflow",
    "name": "Dopasowanie do ekranu",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.11",
    "w3cId": "non-text-contrast",
    "name": "Kontrast elementów nietekstowych",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.12",
    "w3cId": "text-spacing",
    "name": "Odstępy w tekście",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "1.4.13",
    "w3cId": "content-on-hover-or-focus",
    "name": "Treść spod kursora lub fokusu",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "1.4",
    "principle": "1"
  },
  {
    "id": "2.1.1",
    "w3cId": "keyboard",
    "name": "Klawiatura",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.1",
    "principle": "2"
  },
  {
    "id": "2.1.2",
    "w3cId": "no-keyboard-trap",
    "name": "Bez pułapki na klawiaturę",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.1",
    "principle": "2"
  },
  {
    "id": "2.1.3",
    "w3cId": "keyboard-no-exception",
    "name": "Klawiatura (bez wyjątków)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.1",
    "principle": "2"
  },
  {
    "id": "2.1.4",
    "w3cId": "character-key-shortcuts",
    "name": "Jednoznakowe skróty klawiaturowe",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.1",
    "principle": "2"
  },
  {
    "id": "2.2.1",
    "w3cId": "timing-adjustable",
    "name": "Dostosowanie czasu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.2.2",
    "w3cId": "pause-stop-hide",
    "name": "Pauza, zatrzymanie, ukrycie",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.2.3",
    "w3cId": "no-timing",
    "name": "Bez ograniczeń czasowych",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.2.4",
    "w3cId": "interruptions",
    "name": "Przerywanie",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.2.5",
    "w3cId": "re-authenticating",
    "name": "Ponowne potwierdzenie autentyczności",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.2.6",
    "w3cId": "timeouts",
    "name": "Ostrzeżenie o limicie czasu",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.2",
    "principle": "2"
  },
  {
    "id": "2.3.1",
    "w3cId": "three-flashes-or-below-threshold",
    "name": "Trzy błyski lub wartości poniżej progu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.3",
    "principle": "2"
  },
  {
    "id": "2.3.2",
    "w3cId": "three-flashes",
    "name": "Trzy błyski",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.3",
    "principle": "2"
  },
  {
    "id": "2.3.3",
    "w3cId": "animation-from-interactions",
    "name": "Animacja po interakcji",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.3",
    "principle": "2"
  },
  {
    "id": "2.4.1",
    "w3cId": "bypass-blocks",
    "name": "Możliwość pominięcia bloków",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.2",
    "w3cId": "page-titled",
    "name": "Tytuł strony",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.3",
    "w3cId": "focus-order",
    "name": "Kolejność fokusu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.4",
    "w3cId": "link-purpose-in-context",
    "name": "Cel łącza (w kontekście)",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.5",
    "w3cId": "multiple-ways",
    "name": "Wiele dróg",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.6",
    "w3cId": "headings-and-labels",
    "name": "Nagłówki i etykiety",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.7",
    "w3cId": "focus-visible",
    "name": "Widoczny fokus",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.8",
    "w3cId": "location",
    "name": "Lokalizacja",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.9",
    "w3cId": "link-purpose-link-only",
    "name": "Cel łącza (z samego łącza)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.10",
    "w3cId": "section-headings",
    "name": "Nagłówki sekcji",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.11",
    "w3cId": "focus-not-obscured-minimum",
    "name": "Fokus niezakryty (minimum)",
    "nameSource": "irdpl",
    "level": "AA",
    "versions": [
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.12",
    "w3cId": "focus-not-obscured-enhanced",
    "name": "Fokus niezakryty (ulepszony)",
    "nameSource": "irdpl",
    "level": "AAA",
    "versions": [
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.4.13",
    "w3cId": "focus-appearance",
    "name": "Wygląd fokusu",
    "nameSource": "irdpl",
    "level": "AAA",
    "versions": [
      "2.2"
    ],
    "guideline": "2.4",
    "principle": "2"
  },
  {
    "id": "2.5.1",
    "w3cId": "pointer-gestures",
    "name": "Gesty dotykowe",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.2",
    "w3cId": "pointer-cancellation",
    "name": "Rezygnacja ze wskazania",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.3",
    "w3cId": "label-in-name",
    "name": "Etykieta w nazwie",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.4",
    "w3cId": "motion-actuation",
    "name": "Aktywowanie ruchem",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.5",
    "w3cId": "target-size-enhanced",
    "name": "Rozmiar celu dotykowego",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.6",
    "w3cId": "concurrent-input-mechanisms",
    "name": "Równoległy mechanizm wprowadzania danych",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.7",
    "w3cId": "dragging-movements",
    "name": "Ruch przeciągania",
    "nameSource": "irdpl",
    "level": "AA",
    "versions": [
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "2.5.8",
    "w3cId": "target-size-minimum",
    "name": "Rozmiar celu (minimalny)",
    "nameSource": "irdpl",
    "level": "AA",
    "versions": [
      "2.2"
    ],
    "guideline": "2.5",
    "principle": "2"
  },
  {
    "id": "3.1.1",
    "w3cId": "language-of-page",
    "name": "Język strony",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.1.2",
    "w3cId": "language-of-parts",
    "name": "Język części",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.1.3",
    "w3cId": "unusual-words",
    "name": "Nietypowe słowa",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.1.4",
    "w3cId": "abbreviations",
    "name": "Skróty",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.1.5",
    "w3cId": "reading-level",
    "name": "Poziom umiejętności czytania",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.1.6",
    "w3cId": "pronunciation",
    "name": "Wymowa",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.1",
    "principle": "3"
  },
  {
    "id": "3.2.1",
    "w3cId": "on-focus",
    "name": "Po otrzymaniu fokusu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.2.2",
    "w3cId": "on-input",
    "name": "Podczas wprowadzania danych",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.2.3",
    "w3cId": "consistent-navigation",
    "name": "Spójna nawigacja",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.2.4",
    "w3cId": "consistent-identification",
    "name": "Spójna identyfikacja",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.2.5",
    "w3cId": "change-on-request",
    "name": "Zmiana na żądanie",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.2.6",
    "w3cId": "consistent-help",
    "name": "Spójna pomoc",
    "nameSource": "irdpl",
    "level": "A",
    "versions": [
      "2.2"
    ],
    "guideline": "3.2",
    "principle": "3"
  },
  {
    "id": "3.3.1",
    "w3cId": "error-identification",
    "name": "Identyfikacja błędu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.2",
    "w3cId": "labels-or-instructions",
    "name": "Etykiety lub instrukcje",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.3",
    "w3cId": "error-suggestion",
    "name": "Sugestie korekty błędów",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.4",
    "w3cId": "error-prevention-legal-financial-data",
    "name": "Zapobieganie błędom (prawnym, finansowym, w danych)",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.5",
    "w3cId": "help",
    "name": "Pomoc",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.6",
    "w3cId": "error-prevention-all",
    "name": "Zapobieganie błędom (wszystkim)",
    "nameSource": "w3c",
    "level": "AAA",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.7",
    "w3cId": "redundant-entry",
    "name": "Ponowny wpis",
    "nameSource": "irdpl",
    "level": "A",
    "versions": [
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.8",
    "w3cId": "accessible-authentication-minimum",
    "name": "Dostępne uwierzytelnianie (minimum)",
    "nameSource": "irdpl",
    "level": "AA",
    "versions": [
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "3.3.9",
    "w3cId": "accessible-authentication-enhanced",
    "name": "Dostępne uwierzytelnianie (ulepszone)",
    "nameSource": "irdpl",
    "level": "AAA",
    "versions": [
      "2.2"
    ],
    "guideline": "3.3",
    "principle": "3"
  },
  {
    "id": "4.1.1",
    "w3cId": "parsing",
    "name": "Poprawność kodu",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1"
    ],
    "guideline": "4.1",
    "principle": "4"
  },
  {
    "id": "4.1.2",
    "w3cId": "name-role-value",
    "name": "Nazwa, rola, wartość",
    "nameSource": "w3c",
    "level": "A",
    "versions": [
      "2.0",
      "2.1",
      "2.2"
    ],
    "guideline": "4.1",
    "principle": "4"
  },
  {
    "id": "4.1.3",
    "w3cId": "status-messages",
    "name": "Komunikaty o stanie",
    "nameSource": "w3c",
    "level": "AA",
    "versions": [
      "2.1",
      "2.2"
    ],
    "guideline": "4.1",
    "principle": "4"
  }
] as const;
