/**
 * Imports the WCAG 2.2 structure with Polish names into src/content/wcag.gen.ts.
 * Run by hand with `pnpm import:wcag`; review the diff of the generated file in a PR.
 *
 * Sources:
 * - numbers, W3C ids, levels and versions: the wcag.json that W3C publishes for WCAG 2.2,
 * - Polish names of principles, guidelines and the 78 criteria of WCAG 2.1:
 *   the authorized W3C translation of WCAG 2.1,
 * - Polish names of the 9 criteria new in 2.2: the unofficial IRDPL translation of WCAG 2.2,
 *   because W3C has no authorized Polish translation of 2.2 yet.
 */
import { type } from "arktype";
import { writeFileSync } from "node:fs";

const sources = {
  structure: "https://www.w3.org/WAI/WCAG22/wcag.json",
  w3cPl: "https://www.w3.org/Translations/WCAG21-pl/",
  irdplPl: "https://wcag.irdpl.pl/guidelines/22/",
} as const;

const outFile = new URL("../src/content/wcag.gen.ts", import.meta.url);

// Only the fields we use; ArkType ignores the rest and fails loudly if W3C changes the shape.
const W3cStructure = type({
  principles: type({
    num: "string",
    guidelines: type({
      num: "string",
      successcriteria: type({ num: "string", id: "string", level: "'A' | 'AA' | 'AAA' | ''", versions: "string[]" }).array(),
    }).array(),
  }).array(),
});

async function fetchText(url: string) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${String(response.status)}`);
  return response.text();
}

/**
 * Reads ReSpec headings such as `<bdi class="secno">Kryterium sukcesu 1.1.1 </bdi> Treść nietekstowa`
 * into a map from number to name. Principles use a bare "1. " secno on an h2.
 */
function readHeadings(html: string) {
  const flat = html.replace(/\s+/g, " ");
  const names = new Map<string, string>();
  const levels = new Map<string, string>();
  for (const [, tag, secno = "", rest = ""] of flat.matchAll(/<h([2-4])[^>]*> ?<bdi class="secno">([^<]*)<\/bdi> ?([^<]*)/g)) {
    const label = secno.trim();
    const name = rest.trim();
    const numbered = /^(?:Wytyczna|Kryterium sukcesu) ([\d.]+)$/.exec(label);
    if (numbered?.[1]) names.set(numbered[1], name);
    else if (tag === "2" && /^[1-4]\.$/.test(label)) names.set(label.slice(0, 1), name);
  }
  for (const [, num = "", level = ""] of flat.matchAll(/Kryterium sukcesu ([\d.]+) <\/bdi>.*?\(Poziom (A{1,3})\)/g)) {
    levels.set(num, level);
  }
  return { names, levels };
}

function pick(map: Map<string, string>, key: string, what: string) {
  const value = map.get(key);
  if (!value) throw new Error(`Missing ${what} for ${key}`);
  return value;
}

const [structureJson, w3cHtml, irdplHtml] = await Promise.all([
  fetchText(sources.structure),
  fetchText(sources.w3cPl),
  fetchText(sources.irdplPl),
]);
const structure = W3cStructure.assert(JSON.parse(structureJson));
const w3c = readHeadings(w3cHtml);
const irdpl = readHeadings(irdplHtml);

const principles = structure.principles.map((p) => ({ num: p.num, name: pick(w3c.names, p.num, "principle name") }));
const guidelines = structure.principles.flatMap((p) =>
  p.guidelines.map((g) => ({ num: g.num, name: pick(w3c.names, g.num, "guideline name"), principle: p.num })),
);
const criteria = structure.principles.flatMap((p) =>
  p.guidelines.flatMap((g) =>
    g.successcriteria.map((c) => {
      const inW3cPl = c.versions.includes("2.1");
      // 4.1.1 has no level in the 2.2 data because it was removed; the 2.1 text still states it.
      const level = c.level || pick(w3c.levels, c.num, "level");
      if (inW3cPl && pick(w3c.levels, c.num, "level") !== level) throw new Error(`Level mismatch for ${c.num}`);
      return {
        id: c.num,
        w3cId: c.id,
        name: inW3cPl ? pick(w3c.names, c.num, "criterion name") : pick(irdpl.names, c.num, "criterion name"),
        nameSource: inW3cPl ? "w3c" : "irdpl",
        level,
        versions: c.versions,
        guideline: g.num,
        principle: p.num,
      };
    }),
  ),
);

const today = new Date().toISOString().slice(0, 10);
const json = (value: unknown) => JSON.stringify(value, null, 2);

writeFileSync(
  outFile,
  `// Generated by scripts/import-wcag.ts on ${today}. Do not edit by hand, rerun \`pnpm import:wcag\`.
// Structure: ${sources.structure}
// Names: ${sources.w3cPl} (nameSource "w3c", authorized translation of WCAG 2.1)
//        ${sources.irdplPl} (nameSource "irdpl", unofficial translation of WCAG 2.2)

export const principles = ${json(principles)} as const;

export const guidelines = ${json(guidelines)} as const;

export const criteria = ${json(criteria)} as const;
`,
);

console.log(`Wrote ${String(criteria.length)} criteria to ${outFile.pathname}`);
