/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrawoRouteImport } from './routes/prawo'
import { Route as SciezkiRouteImport } from './routes/sciezki'
import { Route as SearchIndexDotjsonRouteImport } from './routes/search-index[.]json'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SzukajRouteImport } from './routes/szukaj'
import { Route as KryteriaIndexRouteImport } from './routes/kryteria/index'
import { Route as KryteriaCriterionIdRouteImport } from './routes/kryteria/$criterionId'
import { Route as PraktykaIndexRouteImport } from './routes/praktyka/index'
import { Route as PraktykaSlugRouteImport } from './routes/praktyka/$slug'
import { Route as DemoSlugVariantRouteImport } from './routes/demo/$slug.$variant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoRoute = PrawoRouteImport.update({
  id: '/prawo',
  path: '/prawo',
  getParentRoute: () => rootRouteImport,
} as any)
const SciezkiRoute = SciezkiRouteImport.update({
  id: '/sciezki',
  path: '/sciezki',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexDotjsonRoute = SearchIndexDotjsonRouteImport.update({
  id: '/search-index.json',
  path: '/search-index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SzukajRoute = SzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => rootRouteImport,
} as any)
const KryteriaIndexRoute = KryteriaIndexRouteImport.update({
  id: '/kryteria/',
  path: '/kryteria/',
  getParentRoute: () => rootRouteImport,
} as any)
const KryteriaCriterionIdRoute = KryteriaCriterionIdRouteImport.update({
  id: '/kryteria/$criterionId',
  path: '/kryteria/$criterionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktykaIndexRoute = PraktykaIndexRouteImport.update({
  id: '/praktyka/',
  path: '/praktyka/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktykaSlugRoute = PraktykaSlugRouteImport.update({
  id: '/praktyka/$slug',
  path: '/praktyka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugVariantRoute = DemoSlugVariantRouteImport.update({
  id: '/demo/$slug/$variant',
  path: '/demo/$slug/$variant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/kryteria/': typeof KryteriaIndexRoute
  '/praktyka/': typeof PraktykaIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/kryteria': typeof KryteriaIndexRoute
  '/praktyka': typeof PraktykaIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/kryteria/': typeof KryteriaIndexRoute
  '/praktyka/': typeof PraktykaIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prawo'
    | '/sciezki'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/kryteria/'
    | '/praktyka/'
    | '/demo/$slug/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prawo'
    | '/sciezki'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/kryteria'
    | '/praktyka'
    | '/demo/$slug/$variant'
  id:
    | '__root__'
    | '/'
    | '/prawo'
    | '/sciezki'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/kryteria/'
    | '/praktyka/'
    | '/demo/$slug/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrawoRoute: typeof PrawoRoute
  SciezkiRoute: typeof SciezkiRoute
  SearchIndexDotjsonRoute: typeof SearchIndexDotjsonRoute
  SlownikRoute: typeof SlownikRoute
  SzukajRoute: typeof SzukajRoute
  KryteriaCriterionIdRoute: typeof KryteriaCriterionIdRoute
  PraktykaSlugRoute: typeof PraktykaSlugRoute
  KryteriaIndexRoute: typeof KryteriaIndexRoute
  PraktykaIndexRoute: typeof PraktykaIndexRoute
  DemoSlugVariantRoute: typeof DemoSlugVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo': {
      id: '/prawo'
      path: '/prawo'
      fullPath: '/prawo'
      preLoaderRoute: typeof PrawoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sciezki': {
      id: '/sciezki'
      path: '/sciezki'
      fullPath: '/sciezki'
      preLoaderRoute: typeof SciezkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-index.json': {
      id: '/search-index.json'
      path: '/search-index.json'
      fullPath: '/search-index.json'
      preLoaderRoute: typeof SearchIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szukaj': {
      id: '/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SzukajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kryteria/': {
      id: '/kryteria/'
      path: '/kryteria'
      fullPath: '/kryteria/'
      preLoaderRoute: typeof KryteriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kryteria/$criterionId': {
      id: '/kryteria/$criterionId'
      path: '/kryteria/$criterionId'
      fullPath: '/kryteria/$criterionId'
      preLoaderRoute: typeof KryteriaCriterionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktyka/': {
      id: '/praktyka/'
      path: '/praktyka'
      fullPath: '/praktyka/'
      preLoaderRoute: typeof PraktykaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktyka/$slug': {
      id: '/praktyka/$slug'
      path: '/praktyka/$slug'
      fullPath: '/praktyka/$slug'
      preLoaderRoute: typeof PraktykaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug/$variant': {
      id: '/demo/$slug/$variant'
      path: '/demo/$slug/$variant'
      fullPath: '/demo/$slug/$variant'
      preLoaderRoute: typeof DemoSlugVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrawoRoute: PrawoRoute,
  SciezkiRoute: SciezkiRoute,
  SearchIndexDotjsonRoute: SearchIndexDotjsonRoute,
  SlownikRoute: SlownikRoute,
  SzukajRoute: SzukajRoute,
  KryteriaCriterionIdRoute: KryteriaCriterionIdRoute,
  PraktykaSlugRoute: PraktykaSlugRoute,
  KryteriaIndexRoute: KryteriaIndexRoute,
  PraktykaIndexRoute: PraktykaIndexRoute,
  DemoSlugVariantRoute: DemoSlugVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
