/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapowanieRouteImport } from './routes/mapowanie'
import { Route as SearchIndexDotjsonRouteImport } from './routes/search-index[.]json'
import { Route as SlownikRouteImport } from './routes/slownik'
import { Route as SzukajRouteImport } from './routes/szukaj'
import { Route as KryteriaIndexRouteImport } from './routes/kryteria/index'
import { Route as KryteriaCriterionIdRouteImport } from './routes/kryteria/$criterionId'
import { Route as PraktykaIndexRouteImport } from './routes/praktyka/index'
import { Route as PraktykaSlugRouteImport } from './routes/praktyka/$slug'
import { Route as PrawoIndexRouteImport } from './routes/prawo/index'
import { Route as PrawoEn301549RouteImport } from './routes/prawo/en-301-549'
import { Route as SciezkiIndexRouteImport } from './routes/sciezki/index'
import { Route as DemoSlugVariantRouteImport } from './routes/demo/$slug.$variant'
import { Route as PrawoActIndexRouteImport } from './routes/prawo/$act/index'
import { Route as PrawoActUnitRouteImport } from './routes/prawo/$act/$unit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapowanieRoute = MapowanieRouteImport.update({
  id: '/mapowanie',
  path: '/mapowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexDotjsonRoute = SearchIndexDotjsonRouteImport.update({
  id: '/search-index.json',
  path: '/search-index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SlownikRoute = SlownikRouteImport.update({
  id: '/slownik',
  path: '/slownik',
  getParentRoute: () => rootRouteImport,
} as any)
const SzukajRoute = SzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => rootRouteImport,
} as any)
const KryteriaIndexRoute = KryteriaIndexRouteImport.update({
  id: '/kryteria/',
  path: '/kryteria/',
  getParentRoute: () => rootRouteImport,
} as any)
const KryteriaCriterionIdRoute = KryteriaCriterionIdRouteImport.update({
  id: '/kryteria/$criterionId',
  path: '/kryteria/$criterionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktykaIndexRoute = PraktykaIndexRouteImport.update({
  id: '/praktyka/',
  path: '/praktyka/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktykaSlugRoute = PraktykaSlugRouteImport.update({
  id: '/praktyka/$slug',
  path: '/praktyka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoIndexRoute = PrawoIndexRouteImport.update({
  id: '/prawo/',
  path: '/prawo/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoEn301549Route = PrawoEn301549RouteImport.update({
  id: '/prawo/en-301-549',
  path: '/prawo/en-301-549',
  getParentRoute: () => rootRouteImport,
} as any)
const SciezkiIndexRoute = SciezkiIndexRouteImport.update({
  id: '/sciezki/',
  path: '/sciezki/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugVariantRoute = DemoSlugVariantRouteImport.update({
  id: '/demo/$slug/$variant',
  path: '/demo/$slug/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoActIndexRoute = PrawoActIndexRouteImport.update({
  id: '/prawo/$act/',
  path: '/prawo/$act/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoActUnitRoute = PrawoActUnitRouteImport.update({
  id: '/prawo/$act/$unit',
  path: '/prawo/$act/$unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mapowanie': typeof MapowanieRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/prawo/en-301-549': typeof PrawoEn301549Route
  '/kryteria/': typeof KryteriaIndexRoute
  '/praktyka/': typeof PraktykaIndexRoute
  '/prawo/': typeof PrawoIndexRoute
  '/sciezki/': typeof SciezkiIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
  '/prawo/$act/$unit': typeof PrawoActUnitRoute
  '/prawo/$act/': typeof PrawoActIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mapowanie': typeof MapowanieRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/prawo/en-301-549': typeof PrawoEn301549Route
  '/kryteria': typeof KryteriaIndexRoute
  '/praktyka': typeof PraktykaIndexRoute
  '/prawo': typeof PrawoIndexRoute
  '/sciezki': typeof SciezkiIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
  '/prawo/$act/$unit': typeof PrawoActUnitRoute
  '/prawo/$act': typeof PrawoActIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mapowanie': typeof MapowanieRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/slownik': typeof SlownikRoute
  '/szukaj': typeof SzukajRoute
  '/kryteria/$criterionId': typeof KryteriaCriterionIdRoute
  '/praktyka/$slug': typeof PraktykaSlugRoute
  '/prawo/en-301-549': typeof PrawoEn301549Route
  '/kryteria/': typeof KryteriaIndexRoute
  '/praktyka/': typeof PraktykaIndexRoute
  '/prawo/': typeof PrawoIndexRoute
  '/sciezki/': typeof SciezkiIndexRoute
  '/demo/$slug/$variant': typeof DemoSlugVariantRoute
  '/prawo/$act/$unit': typeof PrawoActUnitRoute
  '/prawo/$act/': typeof PrawoActIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mapowanie'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/prawo/en-301-549'
    | '/kryteria/'
    | '/praktyka/'
    | '/prawo/'
    | '/sciezki/'
    | '/demo/$slug/$variant'
    | '/prawo/$act/$unit'
    | '/prawo/$act/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mapowanie'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/prawo/en-301-549'
    | '/kryteria'
    | '/praktyka'
    | '/prawo'
    | '/sciezki'
    | '/demo/$slug/$variant'
    | '/prawo/$act/$unit'
    | '/prawo/$act'
  id:
    | '__root__'
    | '/'
    | '/mapowanie'
    | '/search-index.json'
    | '/slownik'
    | '/szukaj'
    | '/kryteria/$criterionId'
    | '/praktyka/$slug'
    | '/prawo/en-301-549'
    | '/kryteria/'
    | '/praktyka/'
    | '/prawo/'
    | '/sciezki/'
    | '/demo/$slug/$variant'
    | '/prawo/$act/$unit'
    | '/prawo/$act/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapowanieRoute: typeof MapowanieRoute
  SearchIndexDotjsonRoute: typeof SearchIndexDotjsonRoute
  SlownikRoute: typeof SlownikRoute
  SzukajRoute: typeof SzukajRoute
  KryteriaCriterionIdRoute: typeof KryteriaCriterionIdRoute
  PraktykaSlugRoute: typeof PraktykaSlugRoute
  PrawoEn301549Route: typeof PrawoEn301549Route
  KryteriaIndexRoute: typeof KryteriaIndexRoute
  PraktykaIndexRoute: typeof PraktykaIndexRoute
  PrawoIndexRoute: typeof PrawoIndexRoute
  SciezkiIndexRoute: typeof SciezkiIndexRoute
  DemoSlugVariantRoute: typeof DemoSlugVariantRoute
  PrawoActUnitRoute: typeof PrawoActUnitRoute
  PrawoActIndexRoute: typeof PrawoActIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapowanie': {
      id: '/mapowanie'
      path: '/mapowanie'
      fullPath: '/mapowanie'
      preLoaderRoute: typeof MapowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-index.json': {
      id: '/search-index.json'
      path: '/search-index.json'
      fullPath: '/search-index.json'
      preLoaderRoute: typeof SearchIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slownik': {
      id: '/slownik'
      path: '/slownik'
      fullPath: '/slownik'
      preLoaderRoute: typeof SlownikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szukaj': {
      id: '/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SzukajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kryteria/': {
      id: '/kryteria/'
      path: '/kryteria'
      fullPath: '/kryteria/'
      preLoaderRoute: typeof KryteriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kryteria/$criterionId': {
      id: '/kryteria/$criterionId'
      path: '/kryteria/$criterionId'
      fullPath: '/kryteria/$criterionId'
      preLoaderRoute: typeof KryteriaCriterionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktyka/': {
      id: '/praktyka/'
      path: '/praktyka'
      fullPath: '/praktyka/'
      preLoaderRoute: typeof PraktykaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktyka/$slug': {
      id: '/praktyka/$slug'
      path: '/praktyka/$slug'
      fullPath: '/praktyka/$slug'
      preLoaderRoute: typeof PraktykaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo/': {
      id: '/prawo/'
      path: '/prawo'
      fullPath: '/prawo/'
      preLoaderRoute: typeof PrawoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo/en-301-549': {
      id: '/prawo/en-301-549'
      path: '/prawo/en-301-549'
      fullPath: '/prawo/en-301-549'
      preLoaderRoute: typeof PrawoEn301549RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sciezki/': {
      id: '/sciezki/'
      path: '/sciezki'
      fullPath: '/sciezki/'
      preLoaderRoute: typeof SciezkiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug/$variant': {
      id: '/demo/$slug/$variant'
      path: '/demo/$slug/$variant'
      fullPath: '/demo/$slug/$variant'
      preLoaderRoute: typeof DemoSlugVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo/$act/': {
      id: '/prawo/$act/'
      path: '/prawo/$act'
      fullPath: '/prawo/$act/'
      preLoaderRoute: typeof PrawoActIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo/$act/$unit': {
      id: '/prawo/$act/$unit'
      path: '/prawo/$act/$unit'
      fullPath: '/prawo/$act/$unit'
      preLoaderRoute: typeof PrawoActUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapowanieRoute: MapowanieRoute,
  SearchIndexDotjsonRoute: SearchIndexDotjsonRoute,
  SlownikRoute: SlownikRoute,
  SzukajRoute: SzukajRoute,
  KryteriaCriterionIdRoute: KryteriaCriterionIdRoute,
  PraktykaSlugRoute: PraktykaSlugRoute,
  PrawoEn301549Route: PrawoEn301549Route,
  KryteriaIndexRoute: KryteriaIndexRoute,
  PraktykaIndexRoute: PraktykaIndexRoute,
  PrawoIndexRoute: PrawoIndexRoute,
  SciezkiIndexRoute: SciezkiIndexRoute,
  DemoSlugVariantRoute: DemoSlugVariantRoute,
  PrawoActUnitRoute: PrawoActUnitRoute,
  PrawoActIndexRoute: PrawoActIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
