/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KryteriaRouteImport } from './routes/kryteria'
import { Route as PraktykaRouteImport } from './routes/praktyka'
import { Route as PrawoRouteImport } from './routes/prawo'
import { Route as SciezkiRouteImport } from './routes/sciezki'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KryteriaRoute = KryteriaRouteImport.update({
  id: '/kryteria',
  path: '/kryteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PraktykaRoute = PraktykaRouteImport.update({
  id: '/praktyka',
  path: '/praktyka',
  getParentRoute: () => rootRouteImport,
} as any)
const PrawoRoute = PrawoRouteImport.update({
  id: '/prawo',
  path: '/prawo',
  getParentRoute: () => rootRouteImport,
} as any)
const SciezkiRoute = SciezkiRouteImport.update({
  id: '/sciezki',
  path: '/sciezki',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kryteria': typeof KryteriaRoute
  '/praktyka': typeof PraktykaRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kryteria': typeof KryteriaRoute
  '/praktyka': typeof PraktykaRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kryteria': typeof KryteriaRoute
  '/praktyka': typeof PraktykaRoute
  '/prawo': typeof PrawoRoute
  '/sciezki': typeof SciezkiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kryteria' | '/praktyka' | '/prawo' | '/sciezki'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kryteria' | '/praktyka' | '/prawo' | '/sciezki'
  id: '__root__' | '/' | '/kryteria' | '/praktyka' | '/prawo' | '/sciezki'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KryteriaRoute: typeof KryteriaRoute
  PraktykaRoute: typeof PraktykaRoute
  PrawoRoute: typeof PrawoRoute
  SciezkiRoute: typeof SciezkiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kryteria': {
      id: '/kryteria'
      path: '/kryteria'
      fullPath: '/kryteria'
      preLoaderRoute: typeof KryteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praktyka': {
      id: '/praktyka'
      path: '/praktyka'
      fullPath: '/praktyka'
      preLoaderRoute: typeof PraktykaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prawo': {
      id: '/prawo'
      path: '/prawo'
      fullPath: '/prawo'
      preLoaderRoute: typeof PrawoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sciezki': {
      id: '/sciezki'
      path: '/sciezki'
      fullPath: '/sciezki'
      preLoaderRoute: typeof SciezkiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KryteriaRoute: KryteriaRoute,
  PraktykaRoute: PraktykaRoute,
  PrawoRoute: PrawoRoute,
  SciezkiRoute: SciezkiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
